kind: pipeline
type: docker
name: integration
 
steps:
    - name: code-analysis
      image: boulundeasv/dotnet-sdk-with-java
      commands:
        - dotnet sonarscanner begin /k:"easv-devops_ClassDemo_AY1pyakuEVvRW2O60D2H" /d:sonar.host.url="http://sonar.setgo.dk:9000"  /d:sonar.token="sqp_9a9daa3fb104adb2b66aca58a31947641c9c7812"
        - dotnet build
        - dotnet sonarscanner end /d:sonar.token="sqp_9a9daa3fb104adb2b66aca58a31947641c9c7812"